# FastAPI Backend — Retail Demand Forecasting
# File: main.py
# Model: LightGBM (best model from Notebook 1)
# Author: Nabin Katwal | Retail Demand Forecasting Portfolio Project
#
# HOW TO RUN:
#   pip install fastapi uvicorn joblib lightgbm numpy pandas python-multipart
#   uvicorn main:app --reload --host 0.0.0.0 --port 8000
#
# API DOCS (auto-generated by FastAPI):
#   http://localhost:8000/docs

#  Imports 
from fastapi import FastAPI, HTTPException, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field, validator
from typing import List, Optional
import numpy as np
import pandas as pd
import joblib
import json
import os
import io
from datetime import datetime, timedelta

# APP SETUP
app = FastAPI(
    title="Retail Demand Forecasting API",
    description="""
    ## Demand Forecasting API
    Predict daily sales for store-item combinations using LightGBM.

    ### Endpoints
    - **GET  /health**         — Check if the API is running
    - **GET  /model-info**     — Model metadata and feature list
    - **POST /predict**        — Forecast for a single store-item-date
    - **POST /predict-range**  — Forecast for a date range (one store, one item)
    - **POST /batch-predict**  — Forecast for multiple store-item-date rows (JSON)
    - **POST /upload-predict** — Upload a CSV and get predictions back
    """,
    version="1.0.0"
)

# Allow Streamlit (and any frontend) to call this API
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],      # in production, replace with your domain
    allow_methods=["*"],
    allow_headers=["*"],
)

# ─
# LOAD MODEL & FEATURE LIST ON STARTUP
# ─
MODEL_PATH       = "saved_models/lightgbm.pkl"
FEATURE_LIST_PATH = "saved_models/feature_cols.json"

# Load model once when the server starts (not on every request)
try:
    model = joblib.load(MODEL_PATH)
    print(f" Model loaded from {MODEL_PATH}")
except FileNotFoundError:
    raise RuntimeError(
        f"Model file not found at {MODEL_PATH}. "
        "Please run Notebook 1 first to train and save the model."
    )

try:
    with open(FEATURE_LIST_PATH, "r") as f:
        FEATURE_COLS = json.load(f)
    print(f" Feature list loaded — {len(FEATURE_COLS)} features")
except FileNotFoundError:
    raise RuntimeError(
        f"Feature list not found at {FEATURE_LIST_PATH}. "
        "Please run Notebook 1 first."
    )

# FEATURE ENGINEERING FUNCTION
# (Same logic as Notebook 1 — must match exactly for predictions to be correct)

def engineer_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Given a DataFrame with columns [date, store, item],
    compute all the same features that were used in training.

    For lag/rolling features we cannot compute them from a single row,
    so we fill them with 0 (the model still works — you should pass
    the historical data if you want accurate lag features).
    """
    df = df.copy()
    df["date"] = pd.to_datetime(df["date"])

    #  Calendar features 
    df["year"]        = df["date"].dt.year
    df["month"]       = df["date"].dt.month
    df["day"]         = df["date"].dt.day
    df["dayofweek"]   = df["date"].dt.dayofweek
    df["dayofyear"]   = df["date"].dt.dayofyear
    df["weekofyear"]  = df["date"].dt.isocalendar().week.astype(int)
    df["quarter"]     = df["date"].dt.quarter
    df["is_weekend"]  = (df["dayofweek"] >= 5).astype(int)
    df["is_month_start"] = df["date"].dt.is_month_start.astype(int)
    df["is_month_end"]   = df["date"].dt.is_month_end.astype(int)

    #  Cyclical encoding 
    df["month_sin"]      = np.sin(2 * np.pi * df["month"] / 12)
    df["month_cos"]      = np.cos(2 * np.pi * df["month"] / 12)
    df["dayofweek_sin"]  = np.sin(2 * np.pi * df["dayofweek"] / 7)
    df["dayofweek_cos"]  = np.cos(2 * np.pi * df["dayofweek"] / 7)
    df["dayofyear_sin"]  = np.sin(2 * np.pi * df["dayofyear"] / 365)
    df["dayofyear_cos"]  = np.cos(2 * np.pi * df["dayofyear"] / 365)

    #  Lag / rolling features: fill 0 when no history is provided ─
    # These are filled with 0 for single-row inference.
    # The API also accepts historical_sales to compute them properly.
    lag_cols     = [f"lag_{d}" for d in [7, 14, 21, 28, 90, 180, 365]]
    rolling_cols = []
    for w in [7, 14, 30, 90]:
        rolling_cols += [
            f"rolling_mean_{w}", f"rolling_std_{w}",
            f"rolling_max_{w}",  f"rolling_min_{w}"
        ]
    other_cols = ["expanding_mean", "sales_diff_1", "sales_diff_7"]

    for col in lag_cols + rolling_cols + other_cols:
        if col not in df.columns:
            df[col] = 0.0

    return df


def engineer_features_with_history(
    target_dates: pd.DatetimeIndex,
    store: int,
    item: int,
    history: pd.Series          # pd.Series with DatetimeIndex and sales values
) -> pd.DataFrame:
    """
    Compute lag and rolling features properly when historical sales are provided.
    history: daily sales Series indexed by date (should cover at least 365 days before target_dates[0])
    """
    # Combine history + target dates into one continuous DataFrame
    future = pd.DataFrame({
        "date": target_dates,
        "store": store,
        "item": item,
        "sales": np.nan
    })

    hist_df = pd.DataFrame({
        "date": history.index,
        "store": store,
        "item": item,
        "sales": history.values
    })

    combined = pd.concat([hist_df, future], ignore_index=True)
    combined = combined.sort_values("date").reset_index(drop=True)
    combined["date"] = pd.to_datetime(combined["date"])

    # Calendar features
    combined["year"]        = combined["date"].dt.year
    combined["month"]       = combined["date"].dt.month
    combined["day"]         = combined["date"].dt.day
    combined["dayofweek"]   = combined["date"].dt.dayofweek
    combined["dayofyear"]   = combined["date"].dt.dayofyear
    combined["weekofyear"]  = combined["date"].dt.isocalendar().week.astype(int)
    combined["quarter"]     = combined["date"].dt.quarter
    combined["is_weekend"]  = (combined["dayofweek"] >= 5).astype(int)
    combined["is_month_start"] = combined["date"].dt.is_month_start.astype(int)
    combined["is_month_end"]   = combined["date"].dt.is_month_end.astype(int)

    # Cyclical
    combined["month_sin"]     = np.sin(2 * np.pi * combined["month"] / 12)
    combined["month_cos"]     = np.cos(2 * np.pi * combined["month"] / 12)
    combined["dayofweek_sin"] = np.sin(2 * np.pi * combined["dayofweek"] / 7)
    combined["dayofweek_cos"] = np.cos(2 * np.pi * combined["dayofweek"] / 7)
    combined["dayofyear_sin"] = np.sin(2 * np.pi * combined["dayofyear"] / 365)
    combined["dayofyear_cos"] = np.cos(2 * np.pi * combined["dayofyear"] / 365)

    # Lags
    for lag in [7, 14, 21, 28, 90, 180, 365]:
        combined[f"lag_{lag}"] = combined["sales"].shift(lag)

    # Rolling
    for w in [7, 14, 30, 90]:
        combined[f"rolling_mean_{w}"] = combined["sales"].shift(1).rolling(w, min_periods=1).mean()
        combined[f"rolling_std_{w}"]  = combined["sales"].shift(1).rolling(w, min_periods=1).std()
        combined[f"rolling_max_{w}"]  = combined["sales"].shift(1).rolling(w, min_periods=1).max()
        combined[f"rolling_min_{w}"]  = combined["sales"].shift(1).rolling(w, min_periods=1).min()

    # Expanding
    combined["expanding_mean"] = combined["sales"].shift(1).expanding().mean()

    # Diff
    combined["sales_diff_1"] = combined["sales"].diff(1)
    combined["sales_diff_7"] = combined["sales"].diff(7)

    # Return only the target rows (future dates)
    result = combined[combined["sales"].isna()].copy()
    return result.fillna(0)


def predict_sales(df: pd.DataFrame) -> np.ndarray:
    """
    Given a feature DataFrame, run the model and return predictions.
    Ensures all required feature columns are present (fills missing with 0).
    """
    # Make sure all feature columns exist
    for col in FEATURE_COLS:
        if col not in df.columns:
            df[col] = 0.0

    X = df[FEATURE_COLS].fillna(0)
    preds = model.predict(X)
    preds = np.clip(preds, 0, None)           # no negative sales
    return np.round(preds).astype(int)        # round to whole units

# PYDANTIC SCHEMAS (data validation for request/response)

class SinglePredictRequest(BaseModel):
    """Request body for a single prediction."""
    store: int = Field(..., ge=1, le=10,  description="Store ID (1–10)")
    item:  int = Field(..., ge=1, le=50,  description="Item ID (1–50)")
    date:  str = Field(...,               description="Date in YYYY-MM-DD format")

    @validator("date")
    def validate_date(cls, v):
        try:
            datetime.strptime(v, "%Y-%m-%d")
        except ValueError:
            raise ValueError("Date must be in YYYY-MM-DD format")
        return v

    class Config:
        schema_extra = {
            "example": {"store": 1, "item": 5, "date": "2018-03-15"}
        }


class SinglePredictResponse(BaseModel):
    store:          int
    item:           int
    date:           str
    predicted_sales: int
    model_used:     str = "LightGBM"


class RangePredictRequest(BaseModel):
    """Predict sales for a date range — same store & item."""
    store:      int = Field(..., ge=1, le=10)
    item:       int = Field(..., ge=1, le=50)
    start_date: str = Field(..., description="Start date YYYY-MM-DD")
    end_date:   str = Field(..., description="End date YYYY-MM-DD")

    @validator("start_date", "end_date")
    def validate_date(cls, v):
        try:
            datetime.strptime(v, "%Y-%m-%d")
        except ValueError:
            raise ValueError("Date must be in YYYY-MM-DD format")
        return v

    class Config:
        json_schema_extra = {
            "example": {
                "store": 2, "item": 10,
                "start_date": "2018-01-01", "end_date": "2018-03-31"
            }
        }


class RangePredictResponse(BaseModel):
    store:       int
    item:        int
    start_date:  str
    end_date:    str
    total_days:  int
    total_predicted_sales: int
    forecasts:   List[dict]    # list of {date, predicted_sales}
    model_used:  str = "LightGBM"


class BatchRow(BaseModel):
    store: int = Field(..., ge=1, le=10)
    item:  int = Field(..., ge=1, le=50)
    date:  str


class BatchPredictRequest(BaseModel):
    """Predict for multiple store-item-date rows."""
    rows: List[BatchRow]

    class Config:
        schema_extra = {
            "example": {
                "rows": [
                    {"store": 1, "item": 1, "date": "2018-01-01"},
                    {"store": 1, "item": 2, "date": "2018-01-01"},
                    {"store": 2, "item": 5, "date": "2018-02-14"},
                ]
            }
        }

# ─
# ENDPOINTS
# ─

#  1. Health Check 
@app.get("/health", tags=["Monitoring"])
def health_check():
    """
    Check if the API is running and the model is loaded.
    Returns server status and model info.
    """
    return {
        "status": "ok",
        "model_loaded": model is not None,
        "n_features": len(FEATURE_COLS),
        "timestamp": datetime.now().isoformat()
    }


#  2. Model Info 
@app.get("/model-info", tags=["Model"])
def model_info():
    """
    Returns metadata about the loaded model:
    model type, number of features, and the feature list.
    """
    return {
        "model_type":    "LightGBM Regressor",
        "n_features":    len(FEATURE_COLS),
        "feature_list":  FEATURE_COLS,
        "supported_stores": list(range(1, 11)),
        "supported_items":  list(range(1, 51)),
        "training_data": "2013-01-01 to 2017-12-31",
        "note": "Lag and rolling features are set to 0 for single-row predictions. "
                "Use /predict-range for proper time-series features."
    }


#  3. Single Prediction ─
@app.post("/predict", response_model=SinglePredictResponse, tags=["Prediction"])
def predict_single(request: SinglePredictRequest):
    """
    Predict sales for a **single** store, item, and date.

    - **store**: Store ID (1–10)
    - **item**: Item ID (1–50)
    - **date**: Target date in YYYY-MM-DD format

    Note: For single-row predictions, lag and rolling features are set to 0.
    Use `/predict-range` for better accuracy with full feature computation.
    """
    try:
        # Build a one-row DataFrame
        row = pd.DataFrame([{
            "date":  request.date,
            "store": request.store,
            "item":  request.item,
        }])

        # Compute features
        row_fe = engineer_features(row)

        # Predict
        pred = predict_sales(row_fe)[0]

        return SinglePredictResponse(
            store=request.store,
            item=request.item,
            date=request.date,
            predicted_sales=int(pred)
        )

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Prediction error: {str(e)}")


#  4. Date Range Prediction 
@app.post("/predict-range", response_model=RangePredictResponse, tags=["Prediction"])
def predict_range(request: RangePredictRequest):
    """
    Predict sales for a **date range** for one store-item pair.

    This endpoint generates a full date sequence and computes all features
    (including cyclical calendar features) for every day in the range.

    - Max range: 365 days
    """
    try:
        start = pd.Timestamp(request.start_date)
        end   = pd.Timestamp(request.end_date)

        if start > end:
            raise HTTPException(
                status_code=400,
                detail="start_date must be before or equal to end_date"
            )

        if (end - start).days > 365:
            raise HTTPException(
                status_code=400,
                detail="Date range cannot exceed 365 days per request"
            )

        # Build a DataFrame with one row per day
        date_range = pd.date_range(start=start, end=end, freq="D")
        df = pd.DataFrame({
            "date":  date_range,
            "store": request.store,
            "item":  request.item,
        })

        # Feature engineering
        df_fe = engineer_features(df)

        # Predict
        preds = predict_sales(df_fe)

        # Build response
        forecasts = [
            {"date": str(d.date()), "predicted_sales": int(p)}
            for d, p in zip(date_range, preds)
        ]

        return RangePredictResponse(
            store=request.store,
            item=request.item,
            start_date=request.start_date,
            end_date=request.end_date,
            total_days=len(date_range),
            total_predicted_sales=int(preds.sum()),
            forecasts=forecasts
        )

    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Prediction error: {str(e)}")


#  5. Batch Prediction (JSON) ─
@app.post("/batch-predict", tags=["Prediction"])
def batch_predict(request: BatchPredictRequest):
    """
    Predict sales for **multiple** store-item-date rows sent as JSON.

    Each row must have: store, item, date.
    Returns predictions for all rows.
    Max 10,000 rows per request.
    """
    if len(request.rows) > 10_000:
        raise HTTPException(
            status_code=400,
            detail="Maximum 10,000 rows per batch request"
        )

    try:
        # Convert to DataFrame
        df = pd.DataFrame([r.dict() for r in request.rows])

        # Feature engineering
        df_fe = engineer_features(df)

        # Predict
        preds = predict_sales(df_fe)

        # Build response
        results = []
        for i, row in enumerate(request.rows):
            results.append({
                "store":          row.store,
                "item":           row.item,
                "date":           row.date,
                "predicted_sales": int(preds[i])
            })

        return {
            "total_rows":  len(results),
            "model_used":  "LightGBM",
            "predictions": results
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Batch prediction error: {str(e)}")


#  6. CSV Upload Prediction 
@app.post("/upload-predict", tags=["Prediction"])
async def upload_predict(file: UploadFile = File(...)):
    """
    Upload a **CSV file** with columns [store, item, date] and get predictions.

    The CSV can optionally include an 'id' column (like the Kaggle test.csv).
    Returns a CSV with an added 'predicted_sales' column.

    Example CSV format:
    ```
    id,store,item,date
    0,1,1,2018-01-01
    1,1,1,2018-01-02
    ```
    """
    # Validate file type
    if not file.filename.endswith(".csv"):
        raise HTTPException(
            status_code=400,
            detail="Only CSV files are accepted"
        )

    try:
        # Read uploaded CSV
        contents = await file.read()
        df = pd.read_csv(io.StringIO(contents.decode("utf-8")))

        # Check required columns
        required = {"store", "item", "date"}
        missing  = required - set(df.columns)
        if missing:
            raise HTTPException(
                status_code=400,
                detail=f"CSV missing required columns: {missing}"
            )

        if len(df) > 50_000:
            raise HTTPException(
                status_code=400,
                detail="CSV file too large. Maximum 50,000 rows."
            )

        # Feature engineering
        df_fe = engineer_features(df.copy())

        # Predict
        preds = predict_sales(df_fe)

        # Add predictions to original DataFrame
        df["predicted_sales"] = preds

        # Return as CSV string
        output = df.to_csv(index=False)
        from fastapi.responses import Response
        return Response(
            content=output,
            media_type="text/csv",
            headers={"Content-Disposition": "attachment; filename=predictions.csv"}
        )

    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Upload prediction error: {str(e)}")


#  7. Store Summary ─
@app.get("/store-summary/{store_id}", tags=["Analytics"])
def store_summary(store_id: int, days: int = 30):
    """
    Get a forecast summary for ALL items in a store for the next N days.
    - store_id: Store ID (1–10)
    - days: Number of days to forecast (default 30, max 90)
    """
    if store_id < 1 or store_id > 10:
        raise HTTPException(status_code=400, detail="Store ID must be between 1 and 10")
    if days < 1 or days > 90:
        raise HTTPException(status_code=400, detail="Days must be between 1 and 90")

    try:
        start_date = datetime.today().date()
        end_date   = start_date + timedelta(days=days - 1)
        date_range = pd.date_range(start=start_date, end=end_date, freq="D")
        items      = list(range(1, 51))

        # Build all (item × date) combinations
        rows = []
        for item in items:
            for d in date_range:
                rows.append({"date": d, "store": store_id, "item": item})

        df    = pd.DataFrame(rows)
        df_fe = engineer_features(df)
        preds = predict_sales(df_fe)
        df["predicted_sales"] = preds

        # Summarize by item
        item_summary = (
            df.groupby("item")["predicted_sales"]
            .agg(total_forecast="sum", avg_daily="mean")
            .reset_index()
        )
        item_summary["avg_daily"] = item_summary["avg_daily"].round(1)
        item_summary = item_summary.sort_values("total_forecast", ascending=False)

        return {
            "store_id":             store_id,
            "forecast_start":       str(start_date),
            "forecast_end":         str(end_date),
            "total_days":           days,
            "total_items":          len(items),
            "total_store_forecast": int(df["predicted_sales"].sum()),
            "item_forecasts":       item_summary.to_dict(orient="records")
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Store summary error: {str(e)}")


# ─
# RUN (only when executing this file directly, not through uvicorn)
# ─
if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)