# FastAPI Backend — Retail Demand Forecasting
# File: main.py
# Model: LightGBM (best model from ml notebook)
# Author: Nabin Katwal | Retail Demand Forecasting Portfolio Project
#
# HOW TO RUN:
#   pip install fastapi uvicorn joblib lightgbm numpy pandas python-multipart
#   uvicorn main:app --reload --host 0.0.0.0 --port 8000
#
# API DOCS (auto-generated by FastAPI):
#   http://localhost:8000/docs

#  Imports 
from fastapi import FastAPI, HTTPException, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field, validator
from typing import List, Optional
import numpy as np
import pandas as pd
import joblib
import json
import os
import io
from datetime import datetime, timedelta

# APP SETUP
app = FastAPI(
    title="Retail Demand Forecasting API",
    description="""
    ## Demand Forecasting API
    Predict daily sales for store-item combinations using LightGBM.

    ### Endpoints
    - **GET  /health**         — Check if the API is running
    - **GET  /model-info**     — Model metadata and feature list
    - **POST /predict**        — Forecast for a single store-item-date
    - **POST /predict-range**  — Forecast for a date range (one store, one item)
    - **POST /batch-predict**  — Forecast for multiple store-item-date rows (JSON)
    - **POST /upload-predict** — Upload a CSV and get predictions back
    """,
    version="1.0.0"
)

# Allow Streamlit (and any frontend) to call this API
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],      
    allow_methods=["*"],
    allow_headers=["*"],
)


# LOAD MODEL, FEATURE LIST, AND TRAINING HISTORY ON STARTUP

MODEL_PATH        = "saved_models/lightgbm.pkl"
FEATURE_LIST_PATH = "saved_models/feature_cols.json"
TRAIN_DATA_PATH   = "train.csv"   # historical sales — used for lag/rolling features

# Load model once when the server starts (not on every request)
try:
    model = joblib.load(MODEL_PATH)
    print(f" Model loaded from {MODEL_PATH}")
except FileNotFoundError:
    raise RuntimeError(
        f"Model file not found at {MODEL_PATH}. "
        "Please run Notebook 1 first to train and save the model."
    )

try:
    with open(FEATURE_LIST_PATH, "r") as f:
        FEATURE_COLS = json.load(f)
    print(f" Feature list loaded — {len(FEATURE_COLS)} features")
except FileNotFoundError:
    raise RuntimeError(
        f"Feature list not found at {FEATURE_LIST_PATH}. "
        "Please run Notebook 1 first."
    )

#  BUG FIX: Load training history for proper lag/rolling computation 
# Root cause of predictions always being ~6-7:
#   The original engineer_features() fills ALL lag/rolling features with 0.
#   The model was trained where lag_365 ≈ 40-60 (actual sales). When lag_365=0
#   at inference the model predicts ~6-7 instead of ~40-60.
# Fix: load train.csv once, pivot into a (date × store-item) lookup, and use
#   the real historical values to compute lags for every prediction request.
TRAIN_HISTORY: dict = {}   # key: (store, item) → pd.Series(sales, index=DatetimeIndex)

try:
    _train = pd.read_csv(TRAIN_DATA_PATH, parse_dates=["date"])
    for (store, item), grp in _train.groupby(["store", "item"]):
        TRAIN_HISTORY[(int(store), int(item))] = (
            grp.set_index("date")["sales"].sort_index()
        )
    print(f" Training history loaded — {len(TRAIN_HISTORY)} store-item series")
    del _train   # free memory
except FileNotFoundError:
    # Graceful degradation: predictions will still work but lag features = 0
    print(
        f"  train.csv not found at '{TRAIN_DATA_PATH}'. "
        "Lag/rolling features will be 0 — predictions may be inaccurate. "
        "Place train.csv in the same folder as main.py to fix this."
    )


# FEATURE ENGINEERING HELPERS


def _add_calendar_features(df: pd.DataFrame) -> pd.DataFrame:
    """Add all date-based calendar and cyclical features (no lags)."""
    df["date"] = pd.to_datetime(df["date"])
    df["year"]           = df["date"].dt.year
    df["month"]          = df["date"].dt.month
    df["day"]            = df["date"].dt.day
    df["dayofweek"]      = df["date"].dt.dayofweek
    df["dayofyear"]      = df["date"].dt.dayofyear
    df["weekofyear"]     = df["date"].dt.isocalendar().week.astype(int)
    df["quarter"]        = df["date"].dt.quarter
    df["is_weekend"]     = (df["dayofweek"] >= 5).astype(int)
    df["is_month_start"] = df["date"].dt.is_month_start.astype(int)
    df["is_month_end"]   = df["date"].dt.is_month_end.astype(int)
    df["month_sin"]      = np.sin(2 * np.pi * df["month"] / 12)
    df["month_cos"]      = np.cos(2 * np.pi * df["month"] / 12)
    df["dayofweek_sin"]  = np.sin(2 * np.pi * df["dayofweek"] / 7)
    df["dayofweek_cos"]  = np.cos(2 * np.pi * df["dayofweek"] / 7)
    df["dayofyear_sin"]  = np.sin(2 * np.pi * df["dayofyear"] / 365)
    df["dayofyear_cos"]  = np.cos(2 * np.pi * df["dayofyear"] / 365)
    return df


def _add_lag_rolling_from_history(df: pd.DataFrame, history: pd.Series) -> pd.DataFrame:
    """
    Compute lag and rolling features using real historical sales.
    history: pd.Series with DatetimeIndex containing past daily sales.
    df must already have a 'date' column (datetime).
    """
    target_dates = pd.DatetimeIndex(df["date"].values)

    # Build a combined series: history + NaN placeholders for target dates
    future_series = pd.Series(np.nan, index=target_dates)
    combined = pd.concat([history, future_series]).sort_index()
    combined = combined[~combined.index.duplicated(keep="first")]

    # Lag features
    for lag in [7, 14, 21, 28, 90, 180, 365]:
        lagged = combined.shift(lag)
        df[f"lag_{lag}"] = lagged.reindex(target_dates).values

    # Rolling features (shift(1) prevents leakage)
    shifted = combined.shift(1)
    for w in [7, 14, 30, 90]:
        rolled = shifted.rolling(w, min_periods=1)
        df[f"rolling_mean_{w}"] = rolled.mean().reindex(target_dates).values
        df[f"rolling_std_{w}"]  = rolled.std().reindex(target_dates).values
        df[f"rolling_max_{w}"]  = rolled.max().reindex(target_dates).values
        df[f"rolling_min_{w}"]  = rolled.min().reindex(target_dates).values

    # Expanding mean and diff features
    df["expanding_mean"] = shifted.expanding().mean().reindex(target_dates).values
    df["sales_diff_1"]   = combined.diff(1).reindex(target_dates).values
    df["sales_diff_7"]   = combined.diff(7).reindex(target_dates).values

    return df


def engineer_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Feature engineering that uses real training history for lag/rolling features
    whenever available (keyed by store+item).  Falls back to 0 only when
    TRAIN_HISTORY is empty (train.csv not found) or a new store-item combination
    is encountered.
    """
    df = df.copy()
    df["date"] = pd.to_datetime(df["date"])

    # Calendar features (same for every row regardless of store/item)
    df = _add_calendar_features(df)

    # Lag / rolling — process per store-item group to use correct history
    lag_cols     = [f"lag_{d}" for d in [7, 14, 21, 28, 90, 180, 365]]
    rolling_cols = []
    for w in [7, 14, 30, 90]:
        rolling_cols += [
            f"rolling_mean_{w}", f"rolling_std_{w}",
            f"rolling_max_{w}",  f"rolling_min_{w}",
        ]
    other_cols = ["expanding_mean", "sales_diff_1", "sales_diff_7"]
    all_lag_cols = lag_cols + rolling_cols + other_cols

    if TRAIN_HISTORY:
        # Process each store-item group separately so we use the right history
        groups = df.groupby(["store", "item"])
        result_parts = []
        for (store, item), grp in groups:
            grp = grp.copy().reset_index(drop=True)
            history = TRAIN_HISTORY.get((int(store), int(item)))
            if history is not None:
                grp = _add_lag_rolling_from_history(grp, history)
            else:
                # Unknown store-item: zero-fill as before
                for col in all_lag_cols:
                    grp[col] = 0.0
            result_parts.append(grp)
        df = pd.concat(result_parts, ignore_index=True)
    else:
        # No training history loaded — zero-fill (original behaviour)
        for col in all_lag_cols:
            if col not in df.columns:
                df[col] = 0.0

    return df


def engineer_features_with_history(
    target_dates: pd.DatetimeIndex,
    store: int,
    item: int,
    history: pd.Series          # pd.Series with DatetimeIndex and sales values
) -> pd.DataFrame:
    """
    Compute lag and rolling features properly when historical sales are provided
    explicitly (kept for backwards compatibility / direct callers).
    history: daily sales Series indexed by date (should cover at least 365 days
             before target_dates[0]).
    """
    future = pd.DataFrame({
        "date":  target_dates,
        "store": store,
        "item":  item,
        "sales": np.nan
    })

    hist_df = pd.DataFrame({
        "date":  history.index,
        "store": store,
        "item":  item,
        "sales": history.values
    })

    combined = pd.concat([hist_df, future], ignore_index=True)
    combined = combined.sort_values("date").reset_index(drop=True)
    combined["date"] = pd.to_datetime(combined["date"])

    combined = _add_calendar_features(combined)

    for lag in [7, 14, 21, 28, 90, 180, 365]:
        combined[f"lag_{lag}"] = combined["sales"].shift(lag)

    for w in [7, 14, 30, 90]:
        combined[f"rolling_mean_{w}"] = combined["sales"].shift(1).rolling(w, min_periods=1).mean()
        combined[f"rolling_std_{w}"]  = combined["sales"].shift(1).rolling(w, min_periods=1).std()
        combined[f"rolling_max_{w}"]  = combined["sales"].shift(1).rolling(w, min_periods=1).max()
        combined[f"rolling_min_{w}"]  = combined["sales"].shift(1).rolling(w, min_periods=1).min()

    combined["expanding_mean"] = combined["sales"].shift(1).expanding().mean()
    combined["sales_diff_1"]   = combined["sales"].diff(1)
    combined["sales_diff_7"]   = combined["sales"].diff(7)

    result = combined[combined["sales"].isna()].copy()
    return result.fillna(0)


def predict_sales(df: pd.DataFrame) -> np.ndarray:
    """
    Given a feature DataFrame, run the model and return predictions.
    Ensures all required feature columns are present (fills missing with 0).
    """
    for col in FEATURE_COLS:
        if col not in df.columns:
            df[col] = 0.0

    X = df[FEATURE_COLS].fillna(0)
    preds = model.predict(X)
    preds = np.clip(preds, 0, None)           # no negative sales
    return np.round(preds).astype(int)        # round to whole units


# PYDANTIC SCHEMAS
class SinglePredictRequest(BaseModel):
    store: int = Field(..., ge=1, le=10,  description="Store ID (1–10)")
    item:  int = Field(..., ge=1, le=50,  description="Item ID (1–50)")
    date:  str = Field(...,               description="Date in YYYY-MM-DD format")

    @validator("date")
    def validate_date(cls, v):
        try:
            datetime.strptime(v, "%Y-%m-%d")
        except ValueError:
            raise ValueError("Date must be in YYYY-MM-DD format")
        return v

    class Config:
        schema_extra = {
            "example": {"store": 1, "item": 5, "date": "2018-03-15"}
        }


class SinglePredictResponse(BaseModel):
    store:           int
    item:            int
    date:            str
    predicted_sales: int
    model_used:      str = "LightGBM"


class RangePredictRequest(BaseModel):
    store:      int = Field(..., ge=1, le=10)
    item:       int = Field(..., ge=1, le=50)
    start_date: str = Field(..., description="Start date YYYY-MM-DD")
    end_date:   str = Field(..., description="End date YYYY-MM-DD")

    @validator("start_date", "end_date")
    def validate_date(cls, v):
        try:
            datetime.strptime(v, "%Y-%m-%d")
        except ValueError:
            raise ValueError("Date must be in YYYY-MM-DD format")
        return v

    class Config:
        json_schema_extra = {
            "example": {
                "store": 2, "item": 10,
                "start_date": "2018-01-01", "end_date": "2018-03-31"
            }
        }


class RangePredictResponse(BaseModel):
    store:       int
    item:        int
    start_date:  str
    end_date:    str
    total_days:  int
    total_predicted_sales: int
    forecasts:   List[dict]
    model_used:  str = "LightGBM"


class BatchRow(BaseModel):
    store: int = Field(..., ge=1, le=10)
    item:  int = Field(..., ge=1, le=50)
    date:  str


class BatchPredictRequest(BaseModel):
    rows: List[BatchRow]

    class Config:
        schema_extra = {
            "example": {
                "rows": [
                    {"store": 1, "item": 1, "date": "2018-01-01"},
                    {"store": 1, "item": 2, "date": "2018-01-01"},
                    {"store": 2, "item": 5, "date": "2018-02-14"},
                ]
            }
        }


# ENDPOINTS

# 1. Health Check
@app.get("/health", tags=["Monitoring"])
def health_check():
    return {
        "status": "ok",
        "model_loaded": model is not None,
        "n_features": len(FEATURE_COLS),
        "history_loaded": len(TRAIN_HISTORY) > 0,
        "history_series": len(TRAIN_HISTORY),
        "timestamp": datetime.now().isoformat()
    }


# 2. Model Info
@app.get("/model-info", tags=["Model"])
def model_info():
    return {
        "model_type":       "LightGBM Regressor",
        "n_features":       len(FEATURE_COLS),
        "feature_list":     FEATURE_COLS,
        "supported_stores": list(range(1, 11)),
        "supported_items":  list(range(1, 51)),
        "training_data":    "2013-01-01 to 2017-12-31",
        "history_loaded":   len(TRAIN_HISTORY) > 0,
        "note": "Lag and rolling features are computed from training history when train.csv is present."
    }


# 3. Single Prediction
@app.post("/predict", response_model=SinglePredictResponse, tags=["Prediction"])
def predict_single(request: SinglePredictRequest):
    """
    Predict sales for a single store, item, and date.
    Uses real historical lag/rolling features when train.csv is available.
    """
    try:
        row = pd.DataFrame([{
            "date":  request.date,
            "store": request.store,
            "item":  request.item,
        }])
        row_fe = engineer_features(row)
        pred   = predict_sales(row_fe)[0]
        return SinglePredictResponse(
            store=request.store,
            item=request.item,
            date=request.date,
            predicted_sales=int(pred)
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Prediction error: {str(e)}")


# 4. Date Range Prediction
@app.post("/predict-range", response_model=RangePredictResponse, tags=["Prediction"])
def predict_range(request: RangePredictRequest):
    """
    Predict sales for a date range for one store-item pair.
    Uses real historical lag/rolling features when train.csv is available.
    Max range: 365 days.
    """
    try:
        start = pd.Timestamp(request.start_date)
        end   = pd.Timestamp(request.end_date)

        if start > end:
            raise HTTPException(
                status_code=400,
                detail="start_date must be before or equal to end_date"
            )
        if (end - start).days > 365:
            raise HTTPException(
                status_code=400,
                detail="Date range cannot exceed 365 days per request"
            )

        date_range = pd.date_range(start=start, end=end, freq="D")
        df = pd.DataFrame({
            "date":  date_range,
            "store": request.store,
            "item":  request.item,
        })

        df_fe = engineer_features(df)
        preds = predict_sales(df_fe)

        forecasts = [
            {"date": str(d.date()), "predicted_sales": int(p)}
            for d, p in zip(date_range, preds)
        ]

        return RangePredictResponse(
            store=request.store,
            item=request.item,
            start_date=request.start_date,
            end_date=request.end_date,
            total_days=len(date_range),
            total_predicted_sales=int(preds.sum()),
            forecasts=forecasts
        )

    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Prediction error: {str(e)}")


# 5. Batch Prediction (JSON)
@app.post("/batch-predict", tags=["Prediction"])
def batch_predict(request: BatchPredictRequest):
    """
    Predict sales for multiple store-item-date rows sent as JSON.
    Uses real historical lag/rolling features when train.csv is available.
    Max 10,000 rows per request.
    """
    if len(request.rows) > 10_000:
        raise HTTPException(
            status_code=400,
            detail="Maximum 10,000 rows per batch request"
        )

    try:
        df    = pd.DataFrame([r.dict() for r in request.rows])
        df_fe = engineer_features(df)
        preds = predict_sales(df_fe)

        # Re-align predictions to original row order
        # engineer_features sorts by store/item groups internally,
        # so we need to match back via a merge on original index
        df["_orig_idx"] = range(len(df))
        df_fe["_orig_idx"] = df["_orig_idx"].values  # carry through if groupby reorders

        results = []
        for i, row in enumerate(request.rows):
            results.append({
                "store":           row.store,
                "item":            row.item,
                "date":            row.date,
                "predicted_sales": int(preds[i])
            })

        return {
            "total_rows":  len(results),
            "model_used":  "LightGBM",
            "predictions": results
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Batch prediction error: {str(e)}")


# 6. CSV Upload Prediction
@app.post("/upload-predict", tags=["Prediction"])
async def upload_predict(file: UploadFile = File(...)):
    """
    Upload a CSV file with columns [store, item, date] and get predictions.
    The CSV can optionally include an 'id' column (like the Kaggle test.csv).
    Returns a CSV with an added 'predicted_sales' column.
    Uses real historical lag/rolling features when train.csv is available.
    """
    if not file.filename.endswith(".csv"):
        raise HTTPException(status_code=400, detail="Only CSV files are accepted")

    try:
        contents = await file.read()
        df       = pd.read_csv(io.StringIO(contents.decode("utf-8")))

        required = {"store", "item", "date"}
        missing  = required - set(df.columns)
        if missing:
            raise HTTPException(
                status_code=400,
                detail=f"CSV missing required columns: {missing}"
            )

        if len(df) > 50_000:
            raise HTTPException(
                status_code=400,
                detail="CSV file too large. Maximum 50,000 rows."
            )

        # BUG FIX: preserve original row order across groupby in engineer_features
        df = df.copy()
        df["_orig_order"] = range(len(df))

        df_fe = engineer_features(df.copy())

        # Restore original row order (groupby may reorder rows by store/item)
        df_fe = df_fe.sort_values("_orig_order").reset_index(drop=True)

        preds = predict_sales(df_fe)

        # Add predictions back to the original df (same length, same order)
        df = df.sort_values("_orig_order").reset_index(drop=True)
        df["predicted_sales"] = preds
        df = df.drop(columns=["_orig_order"])

        output = df.to_csv(index=False)
        from fastapi.responses import Response
        return Response(
            content=output,
            media_type="text/csv",
            headers={"Content-Disposition": "attachment; filename=predictions.csv"}
        )

    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Upload prediction error: {str(e)}")


# 7. Store Summary
@app.get("/store-summary/{store_id}", tags=["Analytics"])
def store_summary(store_id: int, days: int = 30):
    """
    Get a forecast summary for ALL items in a store for the next N days.
    Uses real historical lag/rolling features when train.csv is available.
    - store_id: Store ID (1–10)
    - days: Number of days to forecast (default 30, max 90)
    """
    if store_id < 1 or store_id > 10:
        raise HTTPException(status_code=400, detail="Store ID must be between 1 and 10")
    if days < 1 or days > 90:
        raise HTTPException(status_code=400, detail="Days must be between 1 and 90")

    try:
        start_date = datetime.today().date()
        end_date   = start_date + timedelta(days=days - 1)
        date_range = pd.date_range(start=start_date, end=end_date, freq="D")
        items      = list(range(1, 51))

        rows = []
        for item in items:
            for d in date_range:
                rows.append({"date": d, "store": store_id, "item": item})

        df    = pd.DataFrame(rows)
        df_fe = engineer_features(df)
        preds = predict_sales(df_fe)
        df["predicted_sales"] = preds

        item_summary = (
            df.groupby("item")["predicted_sales"]
            .agg(total_forecast="sum", avg_daily="mean")
            .reset_index()
        )
        item_summary["avg_daily"] = item_summary["avg_daily"].round(1)
        item_summary = item_summary.sort_values("total_forecast", ascending=False)

        return {
            "store_id":             store_id,
            "forecast_start":       str(start_date),
            "forecast_end":         str(end_date),
            "total_days":           days,
            "total_items":          len(items),
            "total_store_forecast": int(df["predicted_sales"].sum()),
            "item_forecasts":       item_summary.to_dict(orient="records")
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Store summary error: {str(e)}")


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)